name: IP Monitor

on:
  schedule:
    - cron: "*/5 * * * *" # Run every 5 minutes
  workflow_dispatch: # Allow manual runs

jobs:
  monitor_ip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: pip install requests
      - name: Test Connectivity
        run: |
          ping 1.1.1.1 || echo "1.1.1.1 is unreachable"
          curl -I http://1.1.1.1 || echo "HTTP to 1.1.1.1 failed"
      - name: Run IP Monitor
        env:  # Pass secrets as environment variables
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python monitor.py
